spring:
  datasource:
    generate-unique-name: false
    username: postgres
    password: root
    name: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true

logging:
  file:
    path: /var/logs/
    name: TacoCloud.log
  level:
    root: WARN
    org.springframework.security: DEBUG

taco:
  orders:
    pageSize: 1