spring:
  datasource:
    generate-unique-name: false
    username: root
    password: root
    name: tacocloud #URL: jdbc:h2:mem:tacocloud
  h2:
    console:
      enabled: true
  thymeleaf:
    cache: false
#  security:
#    oauth2:
#      client:
#        registration:
#          facebook:
#            clientId: <facebook client id> // нужна учетная запись приложения в facebook
#            clientSecret: <facebook client secret>
#            scope: email, public_profile