spring:
  datasource:
    generate-unique-name: false
    username: postgres
    password: root
    name: postgres
    url: jdbc:postgresql://localhost:5432/postgres
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: update
