DELETE FROM Ingredient_Ref;
DELETE FROM Taco;
DELETE FROM Taco_order;
DELETE FROM Ingredient;
INSERT INTO Ingredient (id,name,category) VALUES ( 'FLTO', 'Flour Tortilla', 'WRAP' );
INSERT INTO Ingredient (id,name,category) VALUES ( 'COTO', 'Corn Tortilla', 'WRAP' );
INSERT INTO Ingredient (id,name,category) VALUES ( 'GRBF', 'Ground Beef', 'PROTEIN' );
INSERT INTO Ingredient (id,name,category) VALUES ( 'CARN', 'Carnitas', 'PROTEIN' );
INSERT INTO Ingredient (id,name,category) VALUES ( 'TMTO', 'Diced Tomatoes', 'VEGGIES' );
INSERT INTO Ingredient (id,name,category) VALUES ( 'LETC', 'Lettuce', 'VEGGIES' );
INSERT INTO Ingredient (id,name,category) VALUES ( 'CHED', 'Cheddar', 'CHEESE' );
INSERT INTO Ingredient (id,name,category) VALUES ( 'JACK', 'Monterrey Jack', 'CHEESE' );
INSERT INTO Ingredient (id,name,category) VALUES ( 'SLCA', 'Salsa', 'SAUCE' );
INSERT INTO Ingredient (id,name,category) VALUES ( 'SRCR', 'Sour Cream', 'SAUCE' );